name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: test
        run: |
          pip install ."[dev]"
          pytest
